name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests with Maven
      run: mvn test --file pom.xml
      continue-on-error: true

    - name: Generate Test Report
      if: failure()
      run: |
        echo "Test failures detected. Generating report..."
        mkdir -p test-reports
        mv target/surefire-reports/*.xml test-reports/
        grep -E -o '<<< FAILURE! .+ \(.+\)' target/surefire-reports/*.txt | sed 's/<<< FAILURE! //g' > test-failures.txt
        cat test-failures.txt

    - name: Read Test Failures
      if: failure()
      id: read-failures
      run: echo "TEST_FAILURES=$(cat test-failures.txt)" >> $GITHUB_ENV

    - name: Send success message to Telegram
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Все ок"

    - name: Send failure message to Telegram
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Тесты не пройдены. Непройденные тесты:
          ${{ env.TEST_FAILURES }}
